# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - sourceline: 'deb https://dl.bintray.com/libgit2/ci-dependencies trusty libgit2deps'
       key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
    packages:
     - gcc-4.9
     - g++-4.9
     
before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
